package authenticationsystem;

import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;

/**
 *
 * @author lenovo
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
   
    public LoginPage() {
        
        initComponents();
        
        
    } 
//    public boolean validation(String Email,String Password)
//    {
//        boolean flag=false;
//        String email,password;
//        email=jTxtemail.getText();
//        password=jtxtpass.getText();
//        
//        try{
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/students","root","Akshi@123");
//            Statement st=conn.createStatement();
//            String sql=" select * from candidates where Email='" +email+"'and Password=' "+password+ " ' ";
//            ResultSet rs=st.executeQuery(sql);
//            if(rs.next()){
//                dispose();
//                HomePage hp =new HomePage();
//                hp.setVisible(true);
//            }
//            else{
//                JOptionPane.showMessageDialog(null,"incorrect");
//            } 
//                
//            
//                
//            
//        }catch(Exception e){
//            e.printStackTrace();
//            
//        }
//        //return flag;
//    }
    
    
    
           


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtemail = new javax.swing.JTextField();
        jloginButton = new javax.swing.JButton();
        jReglabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 70));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 90, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, 30));

        jTxtemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTxtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 270, 30));

        jloginButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jloginButton.setText("Login");
        jloginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jloginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jReglabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jReglabel.setForeground(new java.awt.Color(242, 242, 242));
        jReglabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jReglabel.setText("create a new account");
        jReglabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jReglabelMouseClicked(evt);
            }
        });
        jPanel2.add(jReglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 220, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Pictures\\bluelock.jpg")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 176, 70, 60));
        jPanel2.add(jtxtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 490, 270));

        pack();
    }// </editor-fold>                        

    private void jloginButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        String email,password;
        email=jTxtemail.getText();
        password=jtxtpass.getText();
        if(email.equals("")){
            JOptionPane.showMessageDialog(this,"please enter the email");
            
        }
       else if(password.equals("")){
            JOptionPane.showMessageDialog(this,"please enter the password");
            
        }
       else{
//          if(validation(email,password)){
//               JOptionPane.showMessageDialog(null,"Login Successfuly");
//               HomePage hp= new HomePage();
//               hp.setVisible(true);
//           }
//           else{
//               JOptionPane.showMessageDialog(null,"Incorrect Email or Password");
//           }
                //String email,password;
        email=jTxtemail.getText();
        password=jtxtpass.getText();
       
       try{
            Class.forName("com.mysql.cj.jdbc.Driver");
           Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/students","root","Akshi@123");
            
            String sql=" select Email,Password from candidates where Email like '% "+email+"%'  ";
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                   String Password=rs.getString("Password").trim() ;
                   String Email=rs.getString("Email");
                   
                   if(Password.equals(password) ){
                       JOptionPane.showMessageDialog(null,"Login Successfuly");
                      //dispose();
                         HomePage hp =new HomePage();
                         hp.setVisible(true);
                        
                   }
                   else{
                JOptionPane.showMessageDialog(null,"Wrong email or password");
                
            } 
              
            }
            else{
                   JOptionPane.showMessageDialog(null,"Wrong email or password");
            }
//                
                
                
            
           
                
             
                
            
        }catch(Exception e){
            e.printStackTrace();
            
        }
       }
       
    }                                            

    private void jReglabelMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        RegistrationPage rgf = new RegistrationPage();
        rgf.setVisible(true);
        rgf.pack();
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jReglabel;
    private javax.swing.JTextField jTxtemail;
    private javax.swing.JButton jloginButton;
    private javax.swing.JPasswordField jtxtpass;
    // End of variables declaration                   
}