package authenticationsystem;

//import com.mysql.cj.xdevapi.Statement;

import java.sql.*;
import java.sql.Connection;
import java.sql.Statement;
//import com.sun.jdi.connect.spi.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class RegistrationPage extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationPage
     */
    
    public RegistrationPage() {
        initComponents();
        
        
        
    }
    public boolean validation(){
        String fname,lname,email,password,confpass,contactno;
        Date DOB;
        fname=jTxtfn.getText();
        lname=jTxtlnln.getText();
        email=jTxtemail.getText();
        password=jTxtpassword.getText();
        confpass=jTxtconfPass.getText();
        DOB=jdateDOB.getDate();
        contactno=jTxtcontactno.getText();
        if(fname.equals("")){
            JOptionPane.showMessageDialog(this,"please enter first name");
            return false;
        }
        if(lname.equals("")){
            JOptionPane.showMessageDialog(this,"please enter last name");
            return false;
        }
        if(email.equals("")){
            JOptionPane.showMessageDialog(this,"please enter the email");
            return false;
        }
        if(password.equals("")){
            JOptionPane.showMessageDialog(this,"please enter password");
            return false;
        }
        if(confpass.equals("")){
            JOptionPane.showMessageDialog(this,"please enter your confirm password");
            return false;
        }
        if(DOB==null){
            JOptionPane.showMessageDialog(this,"please enter date of birth");
            return false;
        }
        if(contactno.equals("")){
            JOptionPane.showMessageDialog(this,"please enter your ContactNo");
            return false;
        }
        if(!password.equals(confpass)){
            JOptionPane.showMessageDialog(this,"password not matched,please try again");
            return false;
        }
        
        return true;
    }
    public void insertIntodb(){
        String FirstName,LastName,Email,Password,ConfPassword,ContactNo;
        String DOB;
       FirstName=jTxtfn.getText();
        LastName=jTxtlnln.getText();
        Email=jTxtemail.getText();
        Password=jTxtpassword.getText();
        ConfPassword=jTxtconfPass.getText();
        SimpleDateFormat dateformat =new SimpleDateFormat("yyyy-MM-dd");
        DOB = dateformat.format(jdateDOB.getDate());
       ContactNo=jTxtcontactno.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/students","root","Akshi@123");
            Statement st=(Statement) conn.createStatement();
            String sql = "insert into candidates values(' " + FirstName + " ' ,' " + LastName + " ' ,' " + Email + " ' ,' "  + Password + " ' ,' " + ConfPassword + " ' ,' " + DOB + " ' , " + ContactNo + "  )";
            st.execute(sql);
            JOptionPane.showMessageDialog(this,"Account created");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
        
            
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbacklabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtpassword = new javax.swing.JPasswordField();
        jTxtfn = new javax.swing.JTextField();
        jTxtcontactno = new javax.swing.JTextField();
        jTxtemail = new javax.swing.JTextField();
        jSignuptbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTxtconfPass = new javax.swing.JPasswordField();
        jdateDOB = new com.toedter.calendar.JDateChooser();
        jTxtlnln = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setForeground(new java.awt.Color(242, 242, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 110, 40));

        jbacklabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbacklabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbacklabel.setText("←");
        jbacklabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbacklabelMouseClicked(evt);
            }
        });
        jPanel1.add(jbacklabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 70));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("First Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Last Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 100, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Email:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 100, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Password:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Confirm Password:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 150, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Birth Date:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 100, 30));
        jPanel2.add(jTxtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, 30));
        jPanel2.add(jTxtfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 180, 30));

        jTxtcontactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtcontactnoActionPerformed(evt);
            }
        });
        jPanel2.add(jTxtcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 180, 30));
        jPanel2.add(jTxtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 290, 30));

        jSignuptbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSignuptbtn.setText("SignUp");
        jSignuptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSignuptbtnActionPerformed(evt);
            }
        });
        jPanel2.add(jSignuptbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 90, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Contact Number:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 140, 30));
        jPanel2.add(jTxtconfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 180, 30));
        jPanel2.add(jdateDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 260, 180, -1));

        jTxtlnln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtlnlnActionPerformed(evt);
            }
        });
        jPanel2.add(jTxtlnln, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 180, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 510, 510));

        pack();
    }// </editor-fold>                        

    private void jTxtcontactnoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jbacklabelMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        LoginPage lp = new LoginPage();
        lp.setVisible(true);
    }                                       

    private void jSignuptbtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if (validation()==true){
        insertIntodb();
//        OTPVerification otp=new OTPVerification();
//        otp.setVisible(true);
        }
//        OTPVerification otp=new OTPVerification();
//        otp.setVisible(true);
    }                                           

    private void jTxtlnlnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jSignuptbtn;
    private javax.swing.JPasswordField jTxtconfPass;
    private javax.swing.JTextField jTxtcontactno;
    private javax.swing.JTextField jTxtemail;
    private javax.swing.JTextField jTxtfn;
    private javax.swing.JTextField jTxtlnln;
    private javax.swing.JPasswordField jTxtpassword;
    private javax.swing.JLabel jbacklabel;
    private com.toedter.calendar.JDateChooser jdateDOB;
    // End of variables declaration                   

    

}